apiVersion: v1
kind: Service
metadata:
  name: my-web-app
  labels:
    app: my-web-app
spec:
  type: NodePort
  selector:
    app: my-web-app
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
